// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comparable.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlgorithmVersion = `-- name: GetAlgorithmVersion :one
SELECT version, name, description, weights, created_at FROM algorithm_version WHERE version=$1 LIMIT 1
`

func (q *Queries) GetAlgorithmVersion(ctx context.Context, version string) (AlgorithmVersion, error) {
	row := q.db.QueryRow(ctx, getAlgorithmVersion, version)
	var i AlgorithmVersion
	err := row.Scan(
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Weights,
		&i.CreatedAt,
	)
	return i, err
}

const getConfig = `-- name: GetConfig :one
SELECT id, version, config, created_at FROM configuration_snapshot WHERE version=$1 LIMIT 1
`

func (q *Queries) GetConfig(ctx context.Context, version string) (ConfigurationSnapshot, error) {
	row := q.db.QueryRow(ctx, getConfig, version)
	var i ConfigurationSnapshot
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getValuationResult = `-- name: GetValuationResult :one
SELECT id, target_parcel_id, snapshot_id, comparable_ids, algorithm_version, configuration_version, outlier_method, weights, statistics, bear_value, base_value, bull_value, confidence, status, query_hash, created_at FROM valuation_result WHERE id=$1 LIMIT 1
`

func (q *Queries) GetValuationResult(ctx context.Context, id pgtype.UUID) (ValuationResult, error) {
	row := q.db.QueryRow(ctx, getValuationResult, id)
	var i ValuationResult
	err := row.Scan(
		&i.ID,
		&i.TargetParcelID,
		&i.SnapshotID,
		&i.ComparableIds,
		&i.AlgorithmVersion,
		&i.ConfigurationVersion,
		&i.OutlierMethod,
		&i.Weights,
		&i.Statistics,
		&i.BearValue,
		&i.BaseValue,
		&i.BullValue,
		&i.Confidence,
		&i.Status,
		&i.QueryHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertComparableResult = `-- name: InsertComparableResult :one
INSERT INTO comparable_result (target_parcel_id, candidate_transaction_id, distance_m, area_similarity, zoning_match, land_use_match, road_access_match, time_score, distance_score, total_score, algorithm_version)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id, target_parcel_id, candidate_transaction_id, distance_m, area_similarity, zoning_match, land_use_match, road_access_match, time_score, distance_score, total_score, algorithm_version, created_at
`

type InsertComparableResultParams struct {
	TargetParcelID         pgtype.UUID    `json:"target_parcel_id"`
	CandidateTransactionID pgtype.UUID    `json:"candidate_transaction_id"`
	DistanceM              pgtype.Numeric `json:"distance_m"`
	AreaSimilarity         pgtype.Numeric `json:"area_similarity"`
	ZoningMatch            bool           `json:"zoning_match"`
	LandUseMatch           bool           `json:"land_use_match"`
	RoadAccessMatch        bool           `json:"road_access_match"`
	TimeScore              pgtype.Numeric `json:"time_score"`
	DistanceScore          pgtype.Numeric `json:"distance_score"`
	TotalScore             pgtype.Numeric `json:"total_score"`
	AlgorithmVersion       string         `json:"algorithm_version"`
}

func (q *Queries) InsertComparableResult(ctx context.Context, arg InsertComparableResultParams) (ComparableResult, error) {
	row := q.db.QueryRow(ctx, insertComparableResult,
		arg.TargetParcelID,
		arg.CandidateTransactionID,
		arg.DistanceM,
		arg.AreaSimilarity,
		arg.ZoningMatch,
		arg.LandUseMatch,
		arg.RoadAccessMatch,
		arg.TimeScore,
		arg.DistanceScore,
		arg.TotalScore,
		arg.AlgorithmVersion,
	)
	var i ComparableResult
	err := row.Scan(
		&i.ID,
		&i.TargetParcelID,
		&i.CandidateTransactionID,
		&i.DistanceM,
		&i.AreaSimilarity,
		&i.ZoningMatch,
		&i.LandUseMatch,
		&i.RoadAccessMatch,
		&i.TimeScore,
		&i.DistanceScore,
		&i.TotalScore,
		&i.AlgorithmVersion,
		&i.CreatedAt,
	)
	return i, err
}

const insertValuationResult = `-- name: InsertValuationResult :one
INSERT INTO valuation_result (target_parcel_id, snapshot_id, comparable_ids, algorithm_version, configuration_version, outlier_method, weights, statistics, bear_value, base_value, bull_value, confidence, query_hash)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id, target_parcel_id, snapshot_id, comparable_ids, algorithm_version, configuration_version, outlier_method, weights, statistics, bear_value, base_value, bull_value, confidence, status, query_hash, created_at
`

type InsertValuationResultParams struct {
	TargetParcelID       pgtype.UUID `json:"target_parcel_id"`
	SnapshotID           pgtype.UUID `json:"snapshot_id"`
	ComparableIds        []byte      `json:"comparable_ids"`
	AlgorithmVersion     string      `json:"algorithm_version"`
	ConfigurationVersion string      `json:"configuration_version"`
	OutlierMethod        string      `json:"outlier_method"`
	Weights              []byte      `json:"weights"`
	Statistics           []byte      `json:"statistics"`
	BearValue            int64       `json:"bear_value"`
	BaseValue            int64       `json:"base_value"`
	BullValue            int64       `json:"bull_value"`
	Confidence           string      `json:"confidence"`
	QueryHash            string      `json:"query_hash"`
}

func (q *Queries) InsertValuationResult(ctx context.Context, arg InsertValuationResultParams) (ValuationResult, error) {
	row := q.db.QueryRow(ctx, insertValuationResult,
		arg.TargetParcelID,
		arg.SnapshotID,
		arg.ComparableIds,
		arg.AlgorithmVersion,
		arg.ConfigurationVersion,
		arg.OutlierMethod,
		arg.Weights,
		arg.Statistics,
		arg.BearValue,
		arg.BaseValue,
		arg.BullValue,
		arg.Confidence,
		arg.QueryHash,
	)
	var i ValuationResult
	err := row.Scan(
		&i.ID,
		&i.TargetParcelID,
		&i.SnapshotID,
		&i.ComparableIds,
		&i.AlgorithmVersion,
		&i.ConfigurationVersion,
		&i.OutlierMethod,
		&i.Weights,
		&i.Statistics,
		&i.BearValue,
		&i.BaseValue,
		&i.BullValue,
		&i.Confidence,
		&i.Status,
		&i.QueryHash,
		&i.CreatedAt,
	)
	return i, err
}

const listComparableResults = `-- name: ListComparableResults :many
SELECT id, target_parcel_id, candidate_transaction_id, distance_m, area_similarity, zoning_match, land_use_match, road_access_match, time_score, distance_score, total_score, algorithm_version, created_at FROM comparable_result WHERE target_parcel_id=$1 ORDER BY total_score DESC, distance_m ASC LIMIT $2
`

type ListComparableResultsParams struct {
	TargetParcelID pgtype.UUID `json:"target_parcel_id"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) ListComparableResults(ctx context.Context, arg ListComparableResultsParams) ([]ComparableResult, error) {
	rows, err := q.db.Query(ctx, listComparableResults, arg.TargetParcelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComparableResult
	for rows.Next() {
		var i ComparableResult
		if err := rows.Scan(
			&i.ID,
			&i.TargetParcelID,
			&i.CandidateTransactionID,
			&i.DistanceM,
			&i.AreaSimilarity,
			&i.ZoningMatch,
			&i.LandUseMatch,
			&i.RoadAccessMatch,
			&i.TimeScore,
			&i.DistanceScore,
			&i.TotalScore,
			&i.AlgorithmVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
