// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"
)

const getAlgorithmVersion = `-- name: GetAlgorithmVersion :one
SELECT version, name, description, weights, created_at FROM algorithm_version WHERE version=$1 LIMIT 1
`

func (q *Queries) GetAlgorithmVersion(ctx context.Context, version string) (AlgorithmVersion, error) {
	row := q.db.QueryRow(ctx, getAlgorithmVersion, version)
	var i AlgorithmVersion
	err := row.Scan(
		&i.Version,
		&i.Name,
		&i.Description,
		&i.Weights,
		&i.CreatedAt,
	)
	return i, err
}

const getConfig = `-- name: GetConfig :one

SELECT id, version, config, created_at FROM configuration_snapshot WHERE version=$1 LIMIT 1
`

// Configuration queries
// Used by config service and provenance lookups
func (q *Queries) GetConfig(ctx context.Context, version string) (ConfigurationSnapshot, error) {
	row := q.db.QueryRow(ctx, getConfig, version)
	var i ConfigurationSnapshot
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}
