// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBatchInsertTransactions implements pgx.CopyFromSource.
type iteratorForBatchInsertTransactions struct {
	rows                 []BatchInsertTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SnapshotID,
		r.rows[0].ImportBatchID,
		r.rows[0].TransactionID,
		r.rows[0].TransactionDate,
		r.rows[0].TransactionType,
		r.rows[0].County,
		r.rows[0].District,
		r.rows[0].Section,
		r.rows[0].LandNumber,
		r.rows[0].TransactionTarget,
		r.rows[0].TotalPrice,
		r.rows[0].UnitPrice,
		r.rows[0].LandAreaSqm,
		r.rows[0].BuildingAreaSqm,
		r.rows[0].UrbanZoning,
		r.rows[0].NonUrbanZoning,
		r.rows[0].LandUseCategory,
		r.rows[0].BuildingType,
		r.rows[0].Floor,
		r.rows[0].Age,
		r.rows[0].ParkingAreaSqm,
		r.rows[0].ParkingPrice,
		r.rows[0].SourceRecordHash,
	}, nil
}

func (r iteratorForBatchInsertTransactions) Err() error {
	return nil
}

func (q *Queries) BatchInsertTransactions(ctx context.Context, arg []BatchInsertTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transaction"}, []string{"snapshot_id", "import_batch_id", "transaction_id", "transaction_date", "transaction_type", "county", "district", "section", "land_number", "transaction_target", "total_price", "unit_price", "land_area_sqm", "building_area_sqm", "urban_zoning", "non_urban_zoning", "land_use_category", "building_type", "floor", "age", "parking_area_sqm", "parking_price", "source_record_hash"}, &iteratorForBatchInsertTransactions{rows: arg})
}
