// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBatchInsertParcelRoadAccess implements pgx.CopyFromSource.
type iteratorForBatchInsertParcelRoadAccess struct {
	rows                 []BatchInsertParcelRoadAccessParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertParcelRoadAccess) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertParcelRoadAccess) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ParcelID,
		r.rows[0].RoadID,
		r.rows[0].DistanceM,
		r.rows[0].NearestPoint,
		r.rows[0].RoadWidthM,
		r.rows[0].AccessType,
		r.rows[0].Source,
		r.rows[0].AlgorithmVersion,
	}, nil
}

func (r iteratorForBatchInsertParcelRoadAccess) Err() error {
	return nil
}

func (q *Queries) BatchInsertParcelRoadAccess(ctx context.Context, arg []BatchInsertParcelRoadAccessParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"parcel_road_access"}, []string{"parcel_id", "road_id", "distance_m", "nearest_point", "road_width_m", "access_type", "source", "algorithm_version"}, &iteratorForBatchInsertParcelRoadAccess{rows: arg})
}

// iteratorForBatchInsertParcels implements pgx.CopyFromSource.
type iteratorForBatchInsertParcels struct {
	rows                 []BatchInsertParcelsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertParcels) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertParcels) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].County,
		r.rows[0].District,
		r.rows[0].Section,
		r.rows[0].LandNumber,
		r.rows[0].AreaSqm,
		r.rows[0].UrbanZoning,
		r.rows[0].LandUseCategory,
		r.rows[0].Geometry,
		r.rows[0].Centroid,
		r.rows[0].Bbox,
		r.rows[0].Source,
		r.rows[0].SourceVersion,
		r.rows[0].ImportBatchID,
	}, nil
}

func (r iteratorForBatchInsertParcels) Err() error {
	return nil
}

func (q *Queries) BatchInsertParcels(ctx context.Context, arg []BatchInsertParcelsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"parcel"}, []string{"county", "district", "section", "land_number", "area_sqm", "urban_zoning", "land_use_category", "geometry", "centroid", "bbox", "source", "source_version", "import_batch_id"}, &iteratorForBatchInsertParcels{rows: arg})
}

// iteratorForBatchInsertRoadSegments implements pgx.CopyFromSource.
type iteratorForBatchInsertRoadSegments struct {
	rows                 []BatchInsertRoadSegmentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertRoadSegments) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertRoadSegments) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].RoadClass,
		r.rows[0].WidthM,
		r.rows[0].WidthSource,
		r.rows[0].Geometry,
		r.rows[0].Source,
		r.rows[0].SourceVersion,
		r.rows[0].ImportBatchID,
	}, nil
}

func (r iteratorForBatchInsertRoadSegments) Err() error {
	return nil
}

func (q *Queries) BatchInsertRoadSegments(ctx context.Context, arg []BatchInsertRoadSegmentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"road_segment"}, []string{"id", "name", "road_class", "width_m", "width_source", "geometry", "source", "source_version", "import_batch_id"}, &iteratorForBatchInsertRoadSegments{rows: arg})
}

// iteratorForBatchInsertTransactions implements pgx.CopyFromSource.
type iteratorForBatchInsertTransactions struct {
	rows                 []BatchInsertTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SnapshotID,
		r.rows[0].ImportBatchID,
		r.rows[0].TransactionID,
		r.rows[0].TransactionDate,
		r.rows[0].TransactionType,
		r.rows[0].County,
		r.rows[0].District,
		r.rows[0].Section,
		r.rows[0].LandNumber,
		r.rows[0].TransactionTarget,
		r.rows[0].TotalPrice,
		r.rows[0].UnitPrice,
		r.rows[0].LandAreaSqm,
		r.rows[0].BuildingAreaSqm,
		r.rows[0].UrbanZoning,
		r.rows[0].NonUrbanZoning,
		r.rows[0].LandUseCategory,
		r.rows[0].BuildingType,
		r.rows[0].Floor,
		r.rows[0].Age,
		r.rows[0].ParkingAreaSqm,
		r.rows[0].ParkingPrice,
		r.rows[0].SourceRecordHash,
	}, nil
}

func (r iteratorForBatchInsertTransactions) Err() error {
	return nil
}

func (q *Queries) BatchInsertTransactions(ctx context.Context, arg []BatchInsertTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transaction"}, []string{"snapshot_id", "import_batch_id", "transaction_id", "transaction_date", "transaction_type", "county", "district", "section", "land_number", "transaction_target", "total_price", "unit_price", "land_area_sqm", "building_area_sqm", "urban_zoning", "non_urban_zoning", "land_use_category", "building_type", "floor", "age", "parking_area_sqm", "parking_price", "source_record_hash"}, &iteratorForBatchInsertTransactions{rows: arg})
}
