// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlgorithmVersion struct {
	Version     string             `json:"version"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Weights     []byte             `json:"weights"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ComparableResult struct {
	ID                     pgtype.UUID        `json:"id"`
	TargetParcelID         pgtype.UUID        `json:"target_parcel_id"`
	CandidateTransactionID pgtype.UUID        `json:"candidate_transaction_id"`
	DistanceM              pgtype.Numeric     `json:"distance_m"`
	AreaSimilarity         pgtype.Numeric     `json:"area_similarity"`
	ZoningMatch            bool               `json:"zoning_match"`
	LandUseMatch           bool               `json:"land_use_match"`
	RoadAccessMatch        bool               `json:"road_access_match"`
	TimeScore              pgtype.Numeric     `json:"time_score"`
	DistanceScore          pgtype.Numeric     `json:"distance_score"`
	TotalScore             pgtype.Numeric     `json:"total_score"`
	AlgorithmVersion       string             `json:"algorithm_version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type ConfigurationSnapshot struct {
	ID        pgtype.UUID        `json:"id"`
	Version   string             `json:"version"`
	Config    []byte             `json:"config"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DatasetSnapshot struct {
	ID                pgtype.UUID        `json:"id"`
	Source            string             `json:"source"`
	SourceVersion     string             `json:"source_version"`
	DownloadedAt      pgtype.Timestamptz `json:"downloaded_at"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	FileName          string             `json:"file_name"`
	FileSha256        string             `json:"file_sha256"`
	RecordCount       int64              `json:"record_count"`
	Status            string             `json:"status"`
	SchemaVersion     string             `json:"schema_version"`
	ImportStartedAt   pgtype.Timestamptz `json:"import_started_at"`
	ImportCompletedAt pgtype.Timestamptz `json:"import_completed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ImportBatch struct {
	ID               pgtype.UUID        `json:"id"`
	SnapshotID       pgtype.UUID        `json:"snapshot_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	Status           string             `json:"status"`
	RecordsProcessed int64              `json:"records_processed"`
	RecordsImported  int64              `json:"records_imported"`
	RecordsFailed    int64              `json:"records_failed"`
	RecordCount      int64              `json:"record_count"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Parcel struct {
	ID              pgtype.UUID        `json:"id"`
	County          string             `json:"county"`
	District        string             `json:"district"`
	Section         string             `json:"section"`
	LandNumber      string             `json:"land_number"`
	AreaSqm         pgtype.Numeric     `json:"area_sqm"`
	UrbanZoning     pgtype.Text        `json:"urban_zoning"`
	LandUseCategory pgtype.Text        `json:"land_use_category"`
	Geometry        string             `json:"geometry"`
	Centroid        interface{}        `json:"centroid"`
	Bbox            interface{}        `json:"bbox"`
	Source          string             `json:"source"`
	SourceVersion   string             `json:"source_version"`
	ImportBatchID   pgtype.UUID        `json:"import_batch_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ParcelGeometry struct {
	ID            pgtype.UUID        `json:"id"`
	ParcelID      pgtype.UUID        `json:"parcel_id"`
	Geometry      string             `json:"geometry"`
	AreaSqm       pgtype.Numeric     `json:"area_sqm"`
	Centroid      interface{}        `json:"centroid"`
	Bbox          interface{}        `json:"bbox"`
	Source        string             `json:"source"`
	SourceVersion string             `json:"source_version"`
	ImportBatchID pgtype.UUID        `json:"import_batch_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ParcelRoadAccess struct {
	ID               pgtype.UUID        `json:"id"`
	ParcelID         pgtype.UUID        `json:"parcel_id"`
	RoadID           pgtype.UUID        `json:"road_id"`
	DistanceM        pgtype.Numeric     `json:"distance_m"`
	NearestPoint     interface{}        `json:"nearest_point"`
	RoadWidthM       pgtype.Numeric     `json:"road_width_m"`
	AccessType       string             `json:"access_type"`
	Source           string             `json:"source"`
	AlgorithmVersion string             `json:"algorithm_version"`
	ComputedAt       pgtype.Timestamptz `json:"computed_at"`
}

type RoadSegment struct {
	ID            pgtype.UUID        `json:"id"`
	Name          pgtype.Text        `json:"name"`
	RoadClass     pgtype.Text        `json:"road_class"`
	WidthM        pgtype.Numeric     `json:"width_m"`
	WidthSource   string             `json:"width_source"`
	Geometry      string             `json:"geometry"`
	Source        string             `json:"source"`
	SourceVersion string             `json:"source_version"`
	ImportBatchID pgtype.UUID        `json:"import_batch_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID                pgtype.UUID        `json:"id"`
	SnapshotID        pgtype.UUID        `json:"snapshot_id"`
	ImportBatchID     pgtype.UUID        `json:"import_batch_id"`
	TransactionID     string             `json:"transaction_id"`
	TransactionDate   pgtype.Date        `json:"transaction_date"`
	TransactionType   string             `json:"transaction_type"`
	County            string             `json:"county"`
	District          string             `json:"district"`
	Section           pgtype.Text        `json:"section"`
	LandNumber        pgtype.Text        `json:"land_number"`
	TransactionTarget pgtype.Text        `json:"transaction_target"`
	TotalPrice        int64              `json:"total_price"`
	UnitPrice         int64              `json:"unit_price"`
	LandAreaSqm       pgtype.Numeric     `json:"land_area_sqm"`
	BuildingAreaSqm   pgtype.Numeric     `json:"building_area_sqm"`
	UrbanZoning       pgtype.Text        `json:"urban_zoning"`
	NonUrbanZoning    pgtype.Text        `json:"non_urban_zoning"`
	LandUseCategory   pgtype.Text        `json:"land_use_category"`
	BuildingType      pgtype.Text        `json:"building_type"`
	Floor             pgtype.Text        `json:"floor"`
	Age               pgtype.Int4        `json:"age"`
	ParkingAreaSqm    pgtype.Numeric     `json:"parking_area_sqm"`
	ParkingPrice      pgtype.Int8        `json:"parking_price"`
	SourceRecordHash  string             `json:"source_record_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type TransactionBuilding struct {
	ID              pgtype.UUID        `json:"id"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	BuildingAreaSqm pgtype.Numeric     `json:"building_area_sqm"`
	BuildingType    pgtype.Text        `json:"building_type"`
	Floor           pgtype.Text        `json:"floor"`
	Age             pgtype.Int4        `json:"age"`
	ParkingAreaSqm  pgtype.Numeric     `json:"parking_area_sqm"`
	ParkingPrice    pgtype.Int8        `json:"parking_price"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type TransactionLand struct {
	ID              pgtype.UUID        `json:"id"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	LandAreaSqm     pgtype.Numeric     `json:"land_area_sqm"`
	LandUseCategory pgtype.Text        `json:"land_use_category"`
	UrbanZoning     pgtype.Text        `json:"urban_zoning"`
	NonUrbanZoning  pgtype.Text        `json:"non_urban_zoning"`
	LandValue       pgtype.Int8        `json:"land_value"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ValuationResult struct {
	ID                   pgtype.UUID        `json:"id"`
	TargetParcelID       pgtype.UUID        `json:"target_parcel_id"`
	SnapshotID           pgtype.UUID        `json:"snapshot_id"`
	ComparableIds        []byte             `json:"comparable_ids"`
	AlgorithmVersion     string             `json:"algorithm_version"`
	ConfigurationVersion string             `json:"configuration_version"`
	OutlierMethod        string             `json:"outlier_method"`
	Weights              []byte             `json:"weights"`
	Statistics           []byte             `json:"statistics"`
	BearValue            int64              `json:"bear_value"`
	BaseValue            int64              `json:"base_value"`
	BullValue            int64              `json:"bull_value"`
	Confidence           string             `json:"confidence"`
	Status               string             `json:"status"`
	QueryHash            string             `json:"query_hash"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}
