// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parcel.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertParcelsParams struct {
	County          string         `json:"county"`
	District        string         `json:"district"`
	Section         string         `json:"section"`
	LandNumber      string         `json:"land_number"`
	AreaSqm         pgtype.Numeric `json:"area_sqm"`
	UrbanZoning     pgtype.Text    `json:"urban_zoning"`
	LandUseCategory pgtype.Text    `json:"land_use_category"`
	Geometry        string         `json:"geometry"`
	Centroid        interface{}    `json:"centroid"`
	Bbox            interface{}    `json:"bbox"`
	Source          string         `json:"source"`
	SourceVersion   string         `json:"source_version"`
	ImportBatchID   pgtype.UUID    `json:"import_batch_id"`
}

const checkRoadAccess = `-- name: CheckRoadAccess :one
SELECT id, parcel_id, road_id, distance_m, nearest_point, road_width_m, access_type, source, algorithm_version, computed_at FROM parcel_road_access WHERE parcel_id=$1 AND algorithm_version=$2 LIMIT 1
`

type CheckRoadAccessParams struct {
	ParcelID         pgtype.UUID `json:"parcel_id"`
	AlgorithmVersion string      `json:"algorithm_version"`
}

func (q *Queries) CheckRoadAccess(ctx context.Context, arg CheckRoadAccessParams) (ParcelRoadAccess, error) {
	row := q.db.QueryRow(ctx, checkRoadAccess, arg.ParcelID, arg.AlgorithmVersion)
	var i ParcelRoadAccess
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.RoadID,
		&i.DistanceM,
		&i.NearestPoint,
		&i.RoadWidthM,
		&i.AccessType,
		&i.Source,
		&i.AlgorithmVersion,
		&i.ComputedAt,
	)
	return i, err
}

const findNearbyRoads = `-- name: FindNearbyRoads :many
SELECT r.id, r.name, r.road_class, r.width_m, r.width_source, r.geometry, r.source, r.source_version, r.import_batch_id, r.created_at, ST_Distance(p.geometry, r.geometry) AS distance_m
FROM parcel p, road_segment r
WHERE p.id=$1 AND ST_DWithin(p.geometry, r.geometry, $2)
ORDER BY distance_m ASC
LIMIT $3
`

type FindNearbyRoadsParams struct {
	ID        pgtype.UUID `json:"id"`
	StDwithin interface{} `json:"st_dwithin"`
	Limit     int32       `json:"limit"`
}

type FindNearbyRoadsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Name          pgtype.Text        `json:"name"`
	RoadClass     pgtype.Text        `json:"road_class"`
	WidthM        pgtype.Numeric     `json:"width_m"`
	WidthSource   string             `json:"width_source"`
	Geometry      string             `json:"geometry"`
	Source        string             `json:"source"`
	SourceVersion string             `json:"source_version"`
	ImportBatchID pgtype.UUID        `json:"import_batch_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DistanceM     interface{}        `json:"distance_m"`
}

func (q *Queries) FindNearbyRoads(ctx context.Context, arg FindNearbyRoadsParams) ([]FindNearbyRoadsRow, error) {
	rows, err := q.db.Query(ctx, findNearbyRoads, arg.ID, arg.StDwithin, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNearbyRoadsRow
	for rows.Next() {
		var i FindNearbyRoadsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoadClass,
			&i.WidthM,
			&i.WidthSource,
			&i.Geometry,
			&i.Source,
			&i.SourceVersion,
			&i.ImportBatchID,
			&i.CreatedAt,
			&i.DistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParcelByID = `-- name: GetParcelByID :one
SELECT id, county, district, section, land_number, area_sqm, urban_zoning, land_use_category, geometry, centroid, bbox, source, source_version, import_batch_id, created_at, updated_at FROM parcel WHERE id = $1 LIMIT 1
`

func (q *Queries) GetParcelByID(ctx context.Context, id pgtype.UUID) (Parcel, error) {
	row := q.db.QueryRow(ctx, getParcelByID, id)
	var i Parcel
	err := row.Scan(
		&i.ID,
		&i.County,
		&i.District,
		&i.Section,
		&i.LandNumber,
		&i.AreaSqm,
		&i.UrbanZoning,
		&i.LandUseCategory,
		&i.Geometry,
		&i.Centroid,
		&i.Bbox,
		&i.Source,
		&i.SourceVersion,
		&i.ImportBatchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParcelByLandNumber = `-- name: GetParcelByLandNumber :one
SELECT id, county, district, section, land_number, area_sqm, urban_zoning, land_use_category, geometry, centroid, bbox, source, source_version, import_batch_id, created_at, updated_at FROM parcel WHERE county=$1 AND district=$2 AND section=$3 AND land_number=$4 LIMIT 1
`

type GetParcelByLandNumberParams struct {
	County     string `json:"county"`
	District   string `json:"district"`
	Section    string `json:"section"`
	LandNumber string `json:"land_number"`
}

func (q *Queries) GetParcelByLandNumber(ctx context.Context, arg GetParcelByLandNumberParams) (Parcel, error) {
	row := q.db.QueryRow(ctx, getParcelByLandNumber,
		arg.County,
		arg.District,
		arg.Section,
		arg.LandNumber,
	)
	var i Parcel
	err := row.Scan(
		&i.ID,
		&i.County,
		&i.District,
		&i.Section,
		&i.LandNumber,
		&i.AreaSqm,
		&i.UrbanZoning,
		&i.LandUseCategory,
		&i.Geometry,
		&i.Centroid,
		&i.Bbox,
		&i.Source,
		&i.SourceVersion,
		&i.ImportBatchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParcelGeometry = `-- name: GetParcelGeometry :one
SELECT id, geometry, centroid, bbox, area_sqm FROM parcel WHERE id=$1 LIMIT 1
`

type GetParcelGeometryRow struct {
	ID       pgtype.UUID    `json:"id"`
	Geometry string         `json:"geometry"`
	Centroid interface{}    `json:"centroid"`
	Bbox     interface{}    `json:"bbox"`
	AreaSqm  pgtype.Numeric `json:"area_sqm"`
}

func (q *Queries) GetParcelGeometry(ctx context.Context, id pgtype.UUID) (GetParcelGeometryRow, error) {
	row := q.db.QueryRow(ctx, getParcelGeometry, id)
	var i GetParcelGeometryRow
	err := row.Scan(
		&i.ID,
		&i.Geometry,
		&i.Centroid,
		&i.Bbox,
		&i.AreaSqm,
	)
	return i, err
}

const searchParcels = `-- name: SearchParcels :many
SELECT id, county, district, section, land_number, area_sqm, urban_zoning, land_use_category, geometry, centroid, bbox, source, source_version, import_batch_id, created_at, updated_at FROM parcel
WHERE county=$1 AND district=$2
  AND ($3::text IS NULL OR section=$3)
  AND ($4::numeric IS NULL OR area_sqm >= $4)
  AND ($5::numeric IS NULL OR area_sqm <= $5)
ORDER BY section, land_number
LIMIT $6 OFFSET $7
`

type SearchParcelsParams struct {
	County   string         `json:"county"`
	District string         `json:"district"`
	Column3  string         `json:"column_3"`
	Column4  pgtype.Numeric `json:"column_4"`
	Column5  pgtype.Numeric `json:"column_5"`
	Limit    int32          `json:"limit"`
	Offset   int32          `json:"offset"`
}

func (q *Queries) SearchParcels(ctx context.Context, arg SearchParcelsParams) ([]Parcel, error) {
	rows, err := q.db.Query(ctx, searchParcels,
		arg.County,
		arg.District,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parcel
	for rows.Next() {
		var i Parcel
		if err := rows.Scan(
			&i.ID,
			&i.County,
			&i.District,
			&i.Section,
			&i.LandNumber,
			&i.AreaSqm,
			&i.UrbanZoning,
			&i.LandUseCategory,
			&i.Geometry,
			&i.Centroid,
			&i.Bbox,
			&i.Source,
			&i.SourceVersion,
			&i.ImportBatchID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
