// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parcel_road_access.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertParcelRoadAccessParams struct {
	ParcelID         pgtype.UUID    `json:"parcel_id"`
	RoadID           pgtype.UUID    `json:"road_id"`
	DistanceM        pgtype.Numeric `json:"distance_m"`
	NearestPoint     interface{}    `json:"nearest_point"`
	RoadWidthM       pgtype.Numeric `json:"road_width_m"`
	AccessType       string         `json:"access_type"`
	Source           string         `json:"source"`
	AlgorithmVersion string         `json:"algorithm_version"`
}

const createParcelRoadAccess = `-- name: CreateParcelRoadAccess :one
INSERT INTO parcel_road_access (parcel_id, road_id, distance_m, nearest_point, road_width_m, access_type, source, algorithm_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, parcel_id, road_id, distance_m, nearest_point, road_width_m, access_type, source, algorithm_version, computed_at
`

type CreateParcelRoadAccessParams struct {
	ParcelID         pgtype.UUID    `json:"parcel_id"`
	RoadID           pgtype.UUID    `json:"road_id"`
	DistanceM        pgtype.Numeric `json:"distance_m"`
	NearestPoint     interface{}    `json:"nearest_point"`
	RoadWidthM       pgtype.Numeric `json:"road_width_m"`
	AccessType       string         `json:"access_type"`
	Source           string         `json:"source"`
	AlgorithmVersion string         `json:"algorithm_version"`
}

func (q *Queries) CreateParcelRoadAccess(ctx context.Context, arg CreateParcelRoadAccessParams) (ParcelRoadAccess, error) {
	row := q.db.QueryRow(ctx, createParcelRoadAccess,
		arg.ParcelID,
		arg.RoadID,
		arg.DistanceM,
		arg.NearestPoint,
		arg.RoadWidthM,
		arg.AccessType,
		arg.Source,
		arg.AlgorithmVersion,
	)
	var i ParcelRoadAccess
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.RoadID,
		&i.DistanceM,
		&i.NearestPoint,
		&i.RoadWidthM,
		&i.AccessType,
		&i.Source,
		&i.AlgorithmVersion,
		&i.ComputedAt,
	)
	return i, err
}

const deleteParcelRoadAccess = `-- name: DeleteParcelRoadAccess :exec
DELETE FROM parcel_road_access WHERE id = $1
`

func (q *Queries) DeleteParcelRoadAccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteParcelRoadAccess, id)
	return err
}

const getParcelRoadAccessByID = `-- name: GetParcelRoadAccessByID :one
SELECT id, parcel_id, road_id, distance_m, nearest_point, road_width_m, access_type, source, algorithm_version, computed_at FROM parcel_road_access WHERE id = $1 LIMIT 1
`

func (q *Queries) GetParcelRoadAccessByID(ctx context.Context, id pgtype.UUID) (ParcelRoadAccess, error) {
	row := q.db.QueryRow(ctx, getParcelRoadAccessByID, id)
	var i ParcelRoadAccess
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.RoadID,
		&i.DistanceM,
		&i.NearestPoint,
		&i.RoadWidthM,
		&i.AccessType,
		&i.Source,
		&i.AlgorithmVersion,
		&i.ComputedAt,
	)
	return i, err
}

const getParcelRoadAccessByParcelID = `-- name: GetParcelRoadAccessByParcelID :one
SELECT id, parcel_id, road_id, distance_m, nearest_point, road_width_m, access_type, source, algorithm_version, computed_at FROM parcel_road_access WHERE parcel_id = $1 LIMIT 1
`

func (q *Queries) GetParcelRoadAccessByParcelID(ctx context.Context, parcelID pgtype.UUID) (ParcelRoadAccess, error) {
	row := q.db.QueryRow(ctx, getParcelRoadAccessByParcelID, parcelID)
	var i ParcelRoadAccess
	err := row.Scan(
		&i.ID,
		&i.ParcelID,
		&i.RoadID,
		&i.DistanceM,
		&i.NearestPoint,
		&i.RoadWidthM,
		&i.AccessType,
		&i.Source,
		&i.AlgorithmVersion,
		&i.ComputedAt,
	)
	return i, err
}

const listParcelRoadAccess = `-- name: ListParcelRoadAccess :many
SELECT id, parcel_id, road_id, distance_m, nearest_point, road_width_m, access_type, source, algorithm_version, computed_at FROM parcel_road_access ORDER BY computed_at DESC LIMIT $1 OFFSET $2
`

type ListParcelRoadAccessParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListParcelRoadAccess(ctx context.Context, arg ListParcelRoadAccessParams) ([]ParcelRoadAccess, error) {
	rows, err := q.db.Query(ctx, listParcelRoadAccess, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParcelRoadAccess
	for rows.Next() {
		var i ParcelRoadAccess
		if err := rows.Scan(
			&i.ID,
			&i.ParcelID,
			&i.RoadID,
			&i.DistanceM,
			&i.NearestPoint,
			&i.RoadWidthM,
			&i.AccessType,
			&i.Source,
			&i.AlgorithmVersion,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
