// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: road_segment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertRoadSegmentsParams struct {
	ID            pgtype.UUID    `json:"id"`
	Name          pgtype.Text    `json:"name"`
	RoadClass     pgtype.Text    `json:"road_class"`
	WidthM        pgtype.Numeric `json:"width_m"`
	WidthSource   string         `json:"width_source"`
	Geometry      string         `json:"geometry"`
	Source        string         `json:"source"`
	SourceVersion string         `json:"source_version"`
	ImportBatchID pgtype.UUID    `json:"import_batch_id"`
}

const createRoadSegment = `-- name: CreateRoadSegment :one
INSERT INTO road_segment (name, road_class, width_m, width_source, geometry, source, source_version, import_batch_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, name, road_class, width_m, width_source, geometry, source, source_version, import_batch_id, created_at
`

type CreateRoadSegmentParams struct {
	Name          pgtype.Text    `json:"name"`
	RoadClass     pgtype.Text    `json:"road_class"`
	WidthM        pgtype.Numeric `json:"width_m"`
	WidthSource   string         `json:"width_source"`
	Geometry      string         `json:"geometry"`
	Source        string         `json:"source"`
	SourceVersion string         `json:"source_version"`
	ImportBatchID pgtype.UUID    `json:"import_batch_id"`
}

func (q *Queries) CreateRoadSegment(ctx context.Context, arg CreateRoadSegmentParams) (RoadSegment, error) {
	row := q.db.QueryRow(ctx, createRoadSegment,
		arg.Name,
		arg.RoadClass,
		arg.WidthM,
		arg.WidthSource,
		arg.Geometry,
		arg.Source,
		arg.SourceVersion,
		arg.ImportBatchID,
	)
	var i RoadSegment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RoadClass,
		&i.WidthM,
		&i.WidthSource,
		&i.Geometry,
		&i.Source,
		&i.SourceVersion,
		&i.ImportBatchID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoadSegmentByID = `-- name: GetRoadSegmentByID :one
SELECT id, name, road_class, width_m, width_source, geometry, source, source_version, import_batch_id, created_at FROM road_segment WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoadSegmentByID(ctx context.Context, id pgtype.UUID) (RoadSegment, error) {
	row := q.db.QueryRow(ctx, getRoadSegmentByID, id)
	var i RoadSegment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RoadClass,
		&i.WidthM,
		&i.WidthSource,
		&i.Geometry,
		&i.Source,
		&i.SourceVersion,
		&i.ImportBatchID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoadSegmentsByName = `-- name: GetRoadSegmentsByName :many
SELECT id, name, road_class, width_m, width_source, geometry, source, source_version, import_batch_id, created_at FROM road_segment WHERE name ILIKE '%' || $1 || '%' LIMIT 50
`

func (q *Queries) GetRoadSegmentsByName(ctx context.Context, dollar_1 pgtype.Text) ([]RoadSegment, error) {
	rows, err := q.db.Query(ctx, getRoadSegmentsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadSegment
	for rows.Next() {
		var i RoadSegment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoadClass,
			&i.WidthM,
			&i.WidthSource,
			&i.Geometry,
			&i.Source,
			&i.SourceVersion,
			&i.ImportBatchID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoadSegments = `-- name: ListRoadSegments :many
SELECT id, name, road_class, width_m, width_source, geometry, source, source_version, import_batch_id, created_at FROM road_segment ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListRoadSegmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRoadSegments(ctx context.Context, arg ListRoadSegmentsParams) ([]RoadSegment, error) {
	rows, err := q.db.Query(ctx, listRoadSegments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadSegment
	for rows.Next() {
		var i RoadSegment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoadClass,
			&i.WidthM,
			&i.WidthSource,
			&i.Geometry,
			&i.Source,
			&i.SourceVersion,
			&i.ImportBatchID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
