// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshot.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeImportBatch = `-- name: CompleteImportBatch :exec
UPDATE import_batch SET status='COMPLETED', completed_at=NOW(), records_imported=$2 WHERE id=$1
`

type CompleteImportBatchParams struct {
	ID              pgtype.UUID `json:"id"`
	RecordsImported int64       `json:"records_imported"`
}

func (q *Queries) CompleteImportBatch(ctx context.Context, arg CompleteImportBatchParams) error {
	_, err := q.db.Exec(ctx, completeImportBatch, arg.ID, arg.RecordsImported)
	return err
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO import_batch (snapshot_id, status) VALUES ($1, 'RUNNING') RETURNING id, snapshot_id, started_at, completed_at, status, records_processed, records_imported, records_failed, record_count, error_message, created_at
`

func (q *Queries) CreateImportBatch(ctx context.Context, snapshotID pgtype.UUID) (ImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch, snapshotID)
	var i ImportBatch
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Status,
		&i.RecordsProcessed,
		&i.RecordsImported,
		&i.RecordsFailed,
		&i.RecordCount,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO dataset_snapshot (id, source, source_version, file_name, file_sha256, record_count, status, schema_version, published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NULL) RETURNING id, source, source_version, downloaded_at, published_at, file_name, file_sha256, record_count, status, schema_version, import_started_at, import_completed_at, created_at
`

type CreateSnapshotParams struct {
	ID            pgtype.UUID `json:"id"`
	Source        string      `json:"source"`
	SourceVersion string      `json:"source_version"`
	FileName      string      `json:"file_name"`
	FileSha256    string      `json:"file_sha256"`
	RecordCount   int64       `json:"record_count"`
	Status        string      `json:"status"`
	SchemaVersion string      `json:"schema_version"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (DatasetSnapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.ID,
		arg.Source,
		arg.SourceVersion,
		arg.FileName,
		arg.FileSha256,
		arg.RecordCount,
		arg.Status,
		arg.SchemaVersion,
	)
	var i DatasetSnapshot
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceVersion,
		&i.DownloadedAt,
		&i.PublishedAt,
		&i.FileName,
		&i.FileSha256,
		&i.RecordCount,
		&i.Status,
		&i.SchemaVersion,
		&i.ImportStartedAt,
		&i.ImportCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshotByID = `-- name: GetSnapshotByID :one
SELECT id, source, source_version, downloaded_at, published_at, file_name, file_sha256, record_count, status, schema_version, import_started_at, import_completed_at, created_at FROM dataset_snapshot WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSnapshotByID(ctx context.Context, id pgtype.UUID) (DatasetSnapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotByID, id)
	var i DatasetSnapshot
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceVersion,
		&i.DownloadedAt,
		&i.PublishedAt,
		&i.FileName,
		&i.FileSha256,
		&i.RecordCount,
		&i.Status,
		&i.SchemaVersion,
		&i.ImportStartedAt,
		&i.ImportCompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, source, source_version, downloaded_at, published_at, file_name, file_sha256, record_count, status, schema_version, import_started_at, import_completed_at, created_at FROM dataset_snapshot ORDER BY downloaded_at DESC
`

func (q *Queries) ListSnapshots(ctx context.Context) ([]DatasetSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatasetSnapshot
	for rows.Next() {
		var i DatasetSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceVersion,
			&i.DownloadedAt,
			&i.PublishedAt,
			&i.FileName,
			&i.FileSha256,
			&i.RecordCount,
			&i.Status,
			&i.SchemaVersion,
			&i.ImportStartedAt,
			&i.ImportCompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSnapshot = `-- name: LockSnapshot :exec
UPDATE dataset_snapshot SET status='LOCKED', import_completed_at=NOW() WHERE id=$1 AND status='IMPORTING'
`

func (q *Queries) LockSnapshot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockSnapshot, id)
	return err
}
