// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertTransactionsParams struct {
	SnapshotID        pgtype.UUID    `json:"snapshot_id"`
	ImportBatchID     pgtype.UUID    `json:"import_batch_id"`
	TransactionID     string         `json:"transaction_id"`
	TransactionDate   pgtype.Date    `json:"transaction_date"`
	TransactionType   string         `json:"transaction_type"`
	County            string         `json:"county"`
	District          string         `json:"district"`
	Section           pgtype.Text    `json:"section"`
	LandNumber        pgtype.Text    `json:"land_number"`
	TransactionTarget pgtype.Text    `json:"transaction_target"`
	TotalPrice        int64          `json:"total_price"`
	UnitPrice         int64          `json:"unit_price"`
	LandAreaSqm       pgtype.Numeric `json:"land_area_sqm"`
	BuildingAreaSqm   pgtype.Numeric `json:"building_area_sqm"`
	UrbanZoning       pgtype.Text    `json:"urban_zoning"`
	NonUrbanZoning    pgtype.Text    `json:"non_urban_zoning"`
	LandUseCategory   pgtype.Text    `json:"land_use_category"`
	BuildingType      pgtype.Text    `json:"building_type"`
	Floor             pgtype.Text    `json:"floor"`
	Age               pgtype.Int4    `json:"age"`
	ParkingAreaSqm    pgtype.Numeric `json:"parking_area_sqm"`
	ParkingPrice      pgtype.Int8    `json:"parking_price"`
	SourceRecordHash  string         `json:"source_record_hash"`
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, snapshot_id, import_batch_id, transaction_id, transaction_date, transaction_type, county, district, section, land_number, transaction_target, total_price, unit_price, land_area_sqm, building_area_sqm, urban_zoning, non_urban_zoning, land_use_category, building_type, floor, age, parking_area_sqm, parking_price, source_record_hash, created_at FROM transaction WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SnapshotID,
		&i.ImportBatchID,
		&i.TransactionID,
		&i.TransactionDate,
		&i.TransactionType,
		&i.County,
		&i.District,
		&i.Section,
		&i.LandNumber,
		&i.TransactionTarget,
		&i.TotalPrice,
		&i.UnitPrice,
		&i.LandAreaSqm,
		&i.BuildingAreaSqm,
		&i.UrbanZoning,
		&i.NonUrbanZoning,
		&i.LandUseCategory,
		&i.BuildingType,
		&i.Floor,
		&i.Age,
		&i.ParkingAreaSqm,
		&i.ParkingPrice,
		&i.SourceRecordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionPercentiles = `-- name: GetTransactionPercentiles :one
SELECT
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY total_price), 0)::float8 AS median_price,
    COALESCE(percentile_cont(0.25) WITHIN GROUP (ORDER BY total_price), 0)::float8 AS p25_price,
    COALESCE(percentile_cont(0.75) WITHIN GROUP (ORDER BY total_price), 0)::float8 AS p75_price,
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY land_area_sqm), 0)::float8 AS median_land_area,
    COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY building_area_sqm), 0)::float8 AS median_building_area
FROM transaction
WHERE county = $1 AND district = $2 AND section = $3
`

type GetTransactionPercentilesParams struct {
	County   string      `json:"county"`
	District string      `json:"district"`
	Section  pgtype.Text `json:"section"`
}

type GetTransactionPercentilesRow struct {
	MedianPrice        float64 `json:"median_price"`
	P25Price           float64 `json:"p25_price"`
	P75Price           float64 `json:"p75_price"`
	MedianLandArea     float64 `json:"median_land_area"`
	MedianBuildingArea float64 `json:"median_building_area"`
}

// percentile_cont for total_price (p25/p50/p75) and area medians by county/district/section.
func (q *Queries) GetTransactionPercentiles(ctx context.Context, arg GetTransactionPercentilesParams) (GetTransactionPercentilesRow, error) {
	row := q.db.QueryRow(ctx, getTransactionPercentiles, arg.County, arg.District, arg.Section)
	var i GetTransactionPercentilesRow
	err := row.Scan(
		&i.MedianPrice,
		&i.P25Price,
		&i.P75Price,
		&i.MedianLandArea,
		&i.MedianBuildingArea,
	)
	return i, err
}

const getTransactionStats = `-- name: GetTransactionStats :one
SELECT
    COUNT(*)::bigint AS cnt,
    COALESCE(MIN(total_price),0)::bigint AS min_price,
    COALESCE(MAX(total_price),0)::bigint AS max_price,
    COALESCE(AVG(total_price),0)::bigint AS avg_price
FROM transaction
WHERE county = $1 AND district = $2 AND section = $3
`

type GetTransactionStatsParams struct {
	County   string      `json:"county"`
	District string      `json:"district"`
	Section  pgtype.Text `json:"section"`
}

type GetTransactionStatsRow struct {
	Cnt      int64 `json:"cnt"`
	MinPrice int64 `json:"min_price"`
	MaxPrice int64 `json:"max_price"`
	AvgPrice int64 `json:"avg_price"`
}

func (q *Queries) GetTransactionStats(ctx context.Context, arg GetTransactionStatsParams) (GetTransactionStatsRow, error) {
	row := q.db.QueryRow(ctx, getTransactionStats, arg.County, arg.District, arg.Section)
	var i GetTransactionStatsRow
	err := row.Scan(
		&i.Cnt,
		&i.MinPrice,
		&i.MaxPrice,
		&i.AvgPrice,
	)
	return i, err
}

const searchTransactions = `-- name: SearchTransactions :many
SELECT id, snapshot_id, import_batch_id, transaction_id, transaction_date, transaction_type, county, district, section, land_number, transaction_target, total_price, unit_price, land_area_sqm, building_area_sqm, urban_zoning, non_urban_zoning, land_use_category, building_type, floor, age, parking_area_sqm, parking_price, source_record_hash, created_at FROM transaction
WHERE county = $1
  AND district = $2
  AND ($3::text = '' OR section = $3)
  AND ($4::text = '' OR land_number = $4)
  AND ($5::date IS NULL OR transaction_date >= $5)
  AND ($6::date IS NULL OR transaction_date <= $6)
ORDER BY transaction_date DESC, id ASC
LIMIT $7 OFFSET $8
`

type SearchTransactionsParams struct {
	County   string      `json:"county"`
	District string      `json:"district"`
	Column3  string      `json:"column_3"`
	Column4  string      `json:"column_4"`
	Column5  pgtype.Date `json:"column_5"`
	Column6  pgtype.Date `json:"column_6"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, searchTransactions,
		arg.County,
		arg.District,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.SnapshotID,
			&i.ImportBatchID,
			&i.TransactionID,
			&i.TransactionDate,
			&i.TransactionType,
			&i.County,
			&i.District,
			&i.Section,
			&i.LandNumber,
			&i.TransactionTarget,
			&i.TotalPrice,
			&i.UnitPrice,
			&i.LandAreaSqm,
			&i.BuildingAreaSqm,
			&i.UrbanZoning,
			&i.NonUrbanZoning,
			&i.LandUseCategory,
			&i.BuildingType,
			&i.Floor,
			&i.Age,
			&i.ParkingAreaSqm,
			&i.ParkingPrice,
			&i.SourceRecordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
